FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["TestAppDequeue.csproj", "TestAppDequeue/"]
RUN dotnet restore "TestAppDequeue.csproj"
COPY . TestAppDequeue/.
WORKDIR "/src/TestAppDequeue"
RUN dotnet build "TestAppDequeue.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TestAppDequeue.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TestAppDequeue.dll"]