FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["TestAppMq.csproj", "TestAppMq/"]
RUN dotnet restore "TestAppMq.csproj"
COPY . TestAppMq/.
WORKDIR "/src/TestAppMq"
RUN dotnet build "TestAppMq.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TestAppMq.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TestAppMq.dll"]